import { makeStyles, createStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) =>
    createStyles({
        main: {
            width: 'calc(100% - 250px)',
            height: '100vh',
            backgroundColor: '#fff',
            color: '#000',
            position: 'fixed',
            top: 0,
            left: 250,
            zIndex: 99,
            display: 'flex',
            flexDirection: 'column',
            paddingTop: 60,
            padding: '10 20px ',
        },
        mainDown: {
            width: 'calc(100% - 550px)',
            height: '100vh',
            backgroundColor: '#fff',
            color: '#000',
            position: 'fixed',
            top: 0,
            left: 250,
            zIndex: 99,
            display: 'flex',
            flexDirection: 'column',
            paddingTop: 60,
            padding: '10 20px ',
            //transition: '1s',
        },
        sidebar: {
            width: '250px',
            height: '100vh',
            backgroundColor: '#000',
            color: '#fff',
            position: 'fixed',
            top: 0,
            left: 0,
            zIndex: 55,
            display: 'flex',
            flexDirection: 'column',
        },
        topNav: {
            width: '250px',
            height: 40,
            padding: 10,
            backgroundColor: '#1B2631',
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-around',
        },
        navLink: {
            paddingTop: 50,
        },
        topbar: {
            width: 'calc(100% - 250px)',
            height: '60px',
            position: 'fixed',
            borderBottom: '1px inset #E5E7E9',
            backgroundColor: '#EAEDED',
            top: 0,
            left: 250,
            zIndex: 33,
        },
        topbarDown: {
            width: 'calc(100% - 550px)',
            height: '60px',
            position: 'fixed',
            borderBottom: '1px inset #E5E7E9',
            backgroundColor: '#EAEDED',
            top: 0,
            left: 250,
            zIndex: 33,
        },
        smalltopbar: {
            width: 300,
            height: '60px',
            position: 'fixed',
            borderBottom: '1px inset #E5E7E9',
            borderLeft: '1px inset #E5E7E9',
            backgroundColor: '#EAEDED',
            //backgroundColor: 'red',
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-evenly',
            top: 0,
            right: 0,
            zIndex: 333,
        },
        smalltopbarDown: {
            width: 300,
            height: '60px',
            position: 'fixed',
            borderBottom: '1px inset #E5E7E9',
            backgroundColor: '#EAEDED',
            top: 0,
            right: -300,
            zIndex: 33,
        },
        threadBar: {
            width: 300,
            height: '100vh',
            position: 'fixed',
            right: -300,
            top: 0,
        },
        threadBarUp: {
            width: 300,
            height: '100vh',
            position: 'fixed',
            paddingTop: 60,
            overflowY: 'scroll',
            right: 0,
            top: 0,
            //backgroundColor: 'red',
            //transition: '1s',
        },
        content: {
            backgroundColor: '#fff',
            width: '100%',
            height: 'calc(100% - 160px)',
            overflowY: 'scroll',
        },
        bottomTab: {
            width: 'calc(100% - 250px)',
            height: '100px',
            backgroundColor: '#EAEDED',
            padding: '0px 20px',
            position: 'fixed',
            bottom: 0,
            left: 250,
            zIndex: 55,
        },
        bottomTabDown: {
            width: 'calc(100% - 550px)',
            height: '100px',
            backgroundColor: '#EAEDED',
            position: 'fixed',
            bottom: 0,
            left: 250,
            zIndex: 55,
        },
        link: {
            color: '#fff',
            zIndex: 0,
            padding: '10px 25px',
            textDecoration: 'none',
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            fontFamily: 'Arial',
            '&:hover': {
                backgroundColor: '#1B2631',
                color: '#fff',
                textDecoration: 'none',
            },
        },
        title: {
            display: 'flex',
            flexDirection: 'column',
        },
        activeLink: {
            color: '#E74C3C',
            backgroundColor: '#FADBD8',
            zIndex: 0,
            padding: '10px 25px',
            borderTopRightRadius: 10,
            borderBottomRightRadius: 10,
            textDecoration: 'none',
            display: 'flex',
            textAlign: 'center',
            alignItems: 'center',
            '&:hover': {
                backgroundColor: '#F5B7B1',
                textDecoration: 'none',
            },
        },
        btn: {
            margin: '30px 5px',
            paddingLeft: 15, 
            paddingTop: 10,
            paddingBottom: 10,
            width: 'auto',
            display: 'flex', 
            flexDirection: 'row', 
            alignItems: 'center', 
            backgroundColor: '#fff',
            boxShadow: '0px 0px 0px 0.5px rgb(0, 0, 0, 0.1)', 
            borderRadius: '30px',
        },
        //btn2: {
        //    margin: 25, 
        //    display: 'flex', 
        //    flexDirection: 'row', 
        //    alignItems: 'center', 
        //    backgroundColor: 'grey', 
        //    backgroundRadius: '30px',
        //},
    }),
);

export default useStyles;
